version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: VincentPG
    restart: on-failure
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: vincent_db
      TZ: Asia/Bangkok
    ports:
      - '6500:5432'