CREATE TABLE categories (
    id 			UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name 		VARCHAR(50) NOT NULL,
    created_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at 	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at 	TIMESTAMP
);
